apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: crypto-spread-ranking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-storage
  resources:
    requests:
      storage: 5Gi