apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: crypto-spread-ranking
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-storage
  hostPath:
    path: /data/redis
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain