apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: crypto-spread-ranking
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    dir /data
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    rdbchecksum yes
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec